### ISSUE TITLE
Documentation is out of date?

### ISSUE THREAD

**Issue by odow** [zavalab/Plasmo.jl#51]
It looks like you aren't building or updating the documentation?

Last commit to gh-pages was in 2020: https://github.com/zavalab/Plasmo.jl/tree/gh-pages

This came up in a JOSS review you might be interested in https://gitlab.uliege.be/smart_grids/public/gboml/-/issues/1

**Comment by jalving** [comment]
Hey @odow! 

Correct, the documentation has not been updated since v0.4.0. I have been trying to clean up the code a bit, improve coverage, get the MadNLP.jl interface working, etc... I'll make a point to get the docs in good shape.

Thanks for the reference. GBOML looks really cool. I have been intending to develop a distributed optigraph interface to use DSP. It looks like they have made quite a bit progress on that front.

**Comment by anhinga** [comment]
I wonder if it's still the case that it's out of date; the commits in https://github.com/plasmo-dev/Plasmo.jl/tree/gh-pages seem to be recent... 

The link in the `README.md` does seem to be wrong (it points to `zavalab` for documentation, instead of pointing to `plasmo-dev`)...

**Comment by jalving** [comment]
You are correct, the documentation was updated for v0.5. It just isn't as complete as it needs to be. I was planning to do a bit more before I close this issue. The doc link seems to redirect correctly, but you are right it should be updated.

Documentation ideas and enhancements are also welcome :)

**Comment by odow** [comment]
Docs are building again: https://plasmo-dev.github.io/Plasmo.jl/v0.5.3/
